- hosts: all
  become: yes
  remote_user: root
  ignore_errors: yes
  tasks:
   - name: deploy war file in tomcat server
     get_url:
      url: http://172.17.0.2:8082/artifactory/gamutkart-project/gamutgurus.war
      dest: /root/apache-tomcat-9.0.62/webapps
      username: admin
      password: password

      
