- hosts: all
  become: yes
  remote_user: root
  ignore_errors: yes
  tasks:
   - name: install java
      apt:
       name: openjdk-8-jdk 
       state: present
   - name: download tomcat
     get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
      dest: /root
      mode: 777
   - name: extract package
     unarchive:
      src: /root/apache-tomcat-9.0.62.tar.gz
      dest: /root
      remote_src: yes
   - name: copy war file 
     copy:
      src: /target/gamutgurus.war
      dest: /root/apache-tomcat-9.0.62/webapps
   - name: start tomcat
     shell: nohup /root/apache-tomcat-9.0.62/bin/startup.sh
