- hosts: all
  become: yes
  remote_user: root
  ignore_errors: yes
  tasks:
   - name: install git
     apt:
      name: git
      state: present
   - name: Git checkout
     git:
      repo: 'https://github.com/dnyanesh12345678/gamutkart2.git'
      dest: /root/gamutkart
   - name: install maven
     apt:
      name: maven
      state: present
   - name: create package
     shell: cd /root/gamutkart && mvn install
   - name: deploy
     shell: cd /root/gamutkart && ./ansible.sh

      
